pipeline:
  build:
    image: ensime/ensime:v2.x-cache
    pull: true
    commands:
      - host `curl -s http://httpbin.org/ip | jq -r '.origin'` || true ;
      - git log | head -n 20 ; git fetch -q --tags
      - if $(git grep -qE "TODO|FIXME" *) ; then
          echo "Please remove TODO or FIXME. Create an issue at GitHub instead." ;
          exit 1 ;
        fi
      - case $SCALA_VERSION in 2.1[23]*) echo 1.8 > .java-version ; esac ;
        git update-index --assume-unchanged .java-version
      - sbt ++$SCALA_VERSION ";test:compile ;doc";
        if $(! git diff --exit-code --quiet) ; then
          echo "Code formatting does not meet the project's standards:" ;
          git --no-pager diff ;
          exit 1 ;
        fi
      - sbt ++$SCALA_VERSION test pcplod/mimaReportBinaryIssues
      - if [ -z "$DRONE_PULL_REQUEST" ] ; then
          sbt ++$SCALA_VERSION pcplod/publish ;
        fi

matrix:
  SCALA_VERSION:
    - 2.13.0-M1
    - 2.12.3
    - 2.11.11
    - 2.10.6
